### ISSUE TITLE
Consider putting this dist up for adoption

### ISSUE THREAD

**Issue by plicease** [plicease/Devel-ebug#21]
Looks like this dist requires some fairly minor maintenance, I'd be happy to take over if you do not have the time to devote to it.

**Comment by plicease** [comment]
@awwaiid has transferred the GitHub repository to me (thanks!).
I am trying to get hold of @acme, who I think still holds first-come on this dist in PAUSE.

**Comment by acme** [comment]
`Added PLICEASE to co-maintainers of Devel::ebug.`
